# Generated by Django 3.0.5 on 2020-04-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SandyWebApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='pdetail',
            new_name='Project_detail',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='plink',
            new_name='Project_link',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='pname',
            new_name='Project_name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='pnum',
            new_name='Project_num',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='ptech',
            new_name='Project_tech',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rcontent',
            new_name='Review_content',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rname',
            new_name='Review_name',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rtime',
            new_name='Review_time',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='sname',
            new_name='Skill_name',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='snum',
            new_name='Skill_num',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='spercent',
            new_name='Skill_percent',
        ),
    ]
