# Generated by Django 3.0.5 on 2020-04-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SandyWebApp', '0002_auto_20200411_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Project_link',
            field=models.URLField(null=True),
        ),
    ]
